name: Cron Job

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight UTC

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  id-token: write

jobs:
  uv-example:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install

      - name: Run classes.py
        run: uv run classes.py

      - name: Run geneate_map.py
        run: uv run generate_map.py

      - name: commit changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add current_firefighter_I_classes.json docs/index.html
          git commit -m "Automated update of class data and map" || echo "No changes to commit"
          git push